include ../common.mk

# how to test addr-of?  Could be a diff address every time the program is
# executed...
UNIT =	incr decr neg		\
	minus plus 		\
	lnot bnot		\
	lshift atomic fcn_ptr jump
SMOKE =
ALL = $(SMOKE) $(UNIT)

include ../rules.mk
