include ../common.mk

UNIT =	undef_fcn	\
	undef_var	\
	non_int_index	\
	void_return	\
	non_void_return	\
	non_field	\
	non_field2	\
	non_field3	\
	redefined_var	\
	bad_goto	\
	bad_break	\
	bad_continue	\
	spawn_in_transaction	\
	sync_in_transaction	\
	parfor_in_transaction	\
	disallowed_spawn	\
	disallowed_spawn2

SMOKE =
ALL = $(SMOKE) $(UNIT)

include ../rules.mk
