include ../common.mk

UNIT = type-inference for-generic while-generic global_vars static-array switch-basic \
	switch-tuple switch-array switch-enum switch-string while-break vars
SMOKE =
ALL = $(SMOKE) $(UNIT)

include ../rules.mk
